Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,17 +34,27 @@ jobs:
 
   test:
     name: Test
-    runs-on: ubuntu-latest
     needs: build
-
+    runs-on: ubuntu-latest
+  
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      - name: Placeholder Test
+      - name: API Health Check
         run: |
-          echo "Phase 3 will replace this with an API Health Check."
-          echo "Test Passed."
+          STATUS=$(curl -s -o response.json -w "%{http_code}" \
+          -X POST \
+          https://1jwu7qfyrb.execute-api.ap-south-1.amazonaws.com/prod/employee/login \
+          -H "Content-Type: application/json" \
+          -d '{"employee_id":"E001"}')
+  
+          echo "HTTP Status: $STATUS"
+          cat response.json
+  
+          if [ "$STATUS" -ne 200 ]; then
+            echo "API Health Check Failed!"
+            exit 1
+          fi
+  
+          echo "API Health Check Passed!"
 
   deploy:
     name: Deploy
